// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvduexskoxjzjdirdcnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2ZHVleHNrb3hqempkaXJkY250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzYzNDksImV4cCI6MjA2NzQxMjM0OX0.v8KCOZK15hR2mzMAeIKU9pBbhHATzAt1e-OnJBjQBMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});